"""O(1) suffix lookup from pre-computed gngram suffix data.

Loads ~/.gngram-lookup/data/suffixes.parquet once at import into a plain
Python dict. Data generated by morphroot builder/build_gngram_suffixes.py.

The parquet file lives in ~/.gngram-lookup/data/ alongside the other gngram
data files — it is not bundled in the pip package and must be generated
locally by running the morphroot builder.

Related GitHub Issue (morphroot):
    #12 - Pre-compute gngram suffix extraction for O(1) static lookup
    https://github.com/craigtrim/morphroot/issues/12
"""

from __future__ import annotations

from pathlib import Path

_DATA_FILE = Path.home() / ".gngram-lookup" / "data" / "suffixes.parquet"

_SUFFIXES: dict[str, list[str]] | None = None


def _load() -> dict[str, list[str]]:
    global _SUFFIXES
    if _SUFFIXES is None:
        if not _DATA_FILE.exists():
            _SUFFIXES = {}
        else:
            import polars as pl
            _SUFFIXES = {
                row["word"]: row["suffixes"].split("|")
                for row in pl.read_parquet(_DATA_FILE).to_dicts()
            }
    return _SUFFIXES


def get_suffixes(word: str) -> list[str] | None:
    """Return the morphological suffixes for a word in the gngram corpus.

    Requires ~/.gngram-lookup/data/suffixes.parquet to exist (generated by
    running `make gngram-suffixes` in the morphroot repo).

    Args:
        word: Any English word. Case-insensitive.

    Returns:
        List of suffixes in derivation order (innermost first) if the word
        is in gngram (above the build-time frequency threshold) and has
        derivational suffixes, e.g. ["ful", "ly"].
        Empty list [] if the word is in gngram but is monomorphemic.
        None if the word is not in the gngram corpus (or data not installed).

    Examples:
        >>> get_suffixes("happiness")
        ['ness']
        >>> get_suffixes("beautifully")
        ['ful', 'ly']
        >>> get_suffixes("cat")
        []
        >>> get_suffixes("xyz123")
        None
    """
    from gngram_lookup.lookup import exists

    normalized = word.lower().strip()
    if not normalized:
        return None

    table = _load()
    if normalized in table:
        return table[normalized]

    if exists(normalized):
        return []

    return None
